### ISSUE TITLE
Signup crash

### ISSUE THREAD

**Issue by Travmatth** [hatchways/team-fruit-loops#45]
## Expected Behavior
User can navigate to `/signup`, enter their information, and have the `signup`` button redirect them to their profile page.

## Actual Behavior
On clicking `signup`, react application crashes.
Stack trace (appears in browser window):
```
Error: Objects are not valid as a React child (found: object with keys {}). If you meant to render a collection of children, use an array instead.
    in div (created by ForwardRef(Alert))
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by ForwardRef(Alert))
    in ForwardRef(Alert) (created by WithStyles(ForwardRef(Alert)))
    in WithStyles(ForwardRef(Alert)) (at Signup.js:20)
    in Alert (at Signup.js:205)
    in Transition (created by ForwardRef(Grow))
    in ForwardRef(Grow) (created by ForwardRef(Snackbar))
    in div (created by ClickAwayListener)
    in ClickAwayListener (created by ForwardRef(Snackbar))
    in ForwardRef(Snackbar) (created by WithStyles(ForwardRef(Snackbar)))
    in WithStyles(ForwardRef(Snackbar)) (at Signup.js:196)
    in main (created by ForwardRef(Container))
    in ForwardRef(Container) (created by WithStyles(ForwardRef(Container)))
    in WithStyles(ForwardRef(Container)) (at Signup.js:126)
    in Signup (created by Context.Consumer)
    in Route (at App.js:31)
    in Switch (at App.js:29)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:28)
    in ThemeProvider (at App.js:24)
    in App (at src/index.js:7)
```
source code snippet (on browser screen):
```
handleSubmit/</<
src/pages/Signup.js:106

  103 |     })
  104 |     .catch((err) => {
  105 |       setSnackBarMessage(err.response.data.errors);
> 106 |       setSnackbarOpen(true);
      | ^  107 |     });
  108 | })
  109 | .catch((err) => {
```
npm run start (client server):
```
Compiled successfully!

You can now view client in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://10.10.180.41:3000

Note that the development build is not optimized.
To create a production build, use npm run build.

^C
```

npm run dev (backend server):
```
> server@0.0.0 dev /Users/Trav/Projects/team-fruit-loops/server
> nodemon -r dotenv/config ./bin/www

[nodemon] 1.19.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node -r dotenv/config ./bin/www`
Listening on port 3001
Connected to MongoDB
-G8cu6maywo_uolFAAAB connected.
POST /register 201 274.716 ms - 7
POST /login 500 158.034 ms - 13
^C
```

## Steps to Reproduce the Problem

  1. Navigate to `signup` & fill out form fields
  2. Click the `signup` button.

## Specifications

  - Version: dev branch, commit #ab95d4dbd4555438b03e32963e52713340c9c4a2
  - Platform: macOS 10.13.6, Firefox Nightly 85.0a1 (2020-11-19) (64-bit), 6.14.5
  - Subsystem:

**Comment by AltiV** [comment]
I have performed a checkout on that particular commit hash and followed the reproduction steps multiple times, but I am not experiencing any crash issues. I will continue looking into this and may end up just trying to put additional safeguards within the catch statements.

**Comment by AltiV** [comment]
It is difficult for me to fix an issue I can't replicate; I added very small changes in #47 in hopes of better pinpointing/removing the problem. Check this again when you are able to.

**Comment by Travmatth** [comment]
## Notes

```
// client/src/pages/Signup.js:Signup:handleSubmit:95-113
axios
        .post("/register", values)
        .then((res) => {
          // After registering, automatically log in
          axios
            .post("/login", values)
            .then((res) => {
              history.push("/profile");
            })
            .catch((err) => {
              setSnackBarMessage(err.response.data.errors);
              setSnackbarOpen(true);
            });
        })
        .catch((err) => {
          setSnackBarMessage(err.response.data.errors);
          setSnackbarOpen(true);
        })
        .then(() => {});
    }
```

Registers returns 201, `axios.post("/login", values)` is executed

```
//server/routes/login.js:router.post:61-66
.catch((err) => {
  if (process.env.NODE_ENV === 'development') {
    console.log(`Error logging in ${user}: ${err}`);
  }
  res.status(500).json({ errors: err });
});
```

On server side, "/login" fails and catch is executed on `bcrypt` Promise with error:

```
message:'secretOrPrivateKey must have a value'
stack:'Error: secretOrPrivateKey must have a value
	at Object.module.exports [as sign] (/team-fruit-loops/server/node_modules/jsonwebtoken/sign.js:107:20)
  at exports.createAccessToken (/team-fruit-loops/server/utils/auth.js:4:14)
  at bcrypt.compare.then (/team-fruit-loops/server/routes/login.js:37:34)'
```

Server returns `500`

```
//client/src/pags/Signup.js:Signup:105
setSnackBarMessage(err.response.data.errors);
```

is called with `err.response.data.errors === {}`, giving the crash and stack trace shown in the original issue
